import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main> 
        <sectiion className="bg-blue-700 min-h-screen">
        <h1>Hi!</h1>
        </sectiion>
      </main>

      
    </div>
  );
}
